// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpP7wUD8J7Dc6RHBPkPaK_-nFMxnaGN9o',
    appId: '1:301378702774:web:c4524eeaa3dfc06ee48517',
    messagingSenderId: '301378702774',
    projectId: 'appzalo-1b02d',
    authDomain: 'appzalo-1b02d.firebaseapp.com',
    storageBucket: 'appzalo-1b02d.appspot.com',
    measurementId: 'G-SQGJQFKSWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0dMzSixsH9DMLfuOae-orY725r3mR1c8',
    appId: '1:301378702774:android:5c5b33c8e6cc66cee48517',
    messagingSenderId: '301378702774',
    projectId: 'appzalo-1b02d',
    storageBucket: 'appzalo-1b02d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJJRKtVlXjxdakoEwLJxK_T-avNohc6HM',
    appId: '1:301378702774:ios:b37aaa8e96e4871be48517',
    messagingSenderId: '301378702774',
    projectId: 'appzalo-1b02d',
    storageBucket: 'appzalo-1b02d.appspot.com',
    iosBundleId: 'com.example.zaloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJJRKtVlXjxdakoEwLJxK_T-avNohc6HM',
    appId: '1:301378702774:ios:0d2b07ede6442ed6e48517',
    messagingSenderId: '301378702774',
    projectId: 'appzalo-1b02d',
    storageBucket: 'appzalo-1b02d.appspot.com',
    iosBundleId: 'com.example.zaloApp.RunnerTests',
  );
}
